config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter import views
from newsletter.apps import NewsletterConfig
from newsletter.views import ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    NewsletterMessageListView, NewsletterMessageDetailView, NewsletterMessageCreateView, NewsletterMessageUpdateView, \
    NewsletterMessageDeleteView, NewsletterSettingsListView, NewsletterSettingsDetailView, NewsletterSettingsCreateView, \
    NewsletterSettingsUpdateView, NewsletterSettingsDeleteView, NewsletterLogListView

app_name = NewsletterConfig.name


urlpatterns = [

    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/view/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('newslettermessage/', NewsletterMessageListView.as_view(), name='newslettermessage_list'),
    path('newslettermessage/view/<int:pk>/', NewsletterMessageDetailView.as_view(), name='view_newslettermessage'),
    path('newslettermessage/create/', NewsletterMessageCreateView.as_view(), name='create_newslettermessage'),
    path('newslettermessage/edit/<int:pk>/', NewsletterMessageUpdateView.as_view(), name='edit_newslettermessage'),
    path('newslettermessage/delete/<int:pk>/', NewsletterMessageDeleteView.as_view(), name='delete_newslettermessage'),

    path('newslettersettings/', cache_page(60)(NewsletterSettingsListView.as_view()), name='mail_list'),
    path('newslettersettings/view/<int:pk>/', NewsletterSettingsDetailView.as_view(), name='view_mail'),
    path('newslettersettings/create/', NewsletterSettingsCreateView.as_view(), name='create_mail'),
    path('newslettersettings/edit/<int:pk>/', NewsletterSettingsUpdateView.as_view(), name='edit_mail'),
    path('newslettersettings/delete/<int:pk>/', NewsletterSettingsDeleteView.as_view(), name='delete_mail'),

    path('log_list', cache_page(60)(NewsletterLogListView.as_view()), name='log_list'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import generate_new_password, verification, ProfileUpdateView, UserListView, \
    status_user, RegisterUserView, UserLoginView, UserLogoutView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password'),
    path('verification/<str:code>/', verification, name='verification'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('status_user/<int:pk>', status_user, name='status_user'),
]

newsletter/models.py
from dateutil.relativedelta import relativedelta
from django.conf import settings

from django.db import models
from django.utils import timezone
import pytz
from datetime import datetime, timedelta

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    client_email = models.EmailField(unique=True, verbose_name='почта клиента')
    client_fullname = models.CharField(max_length=50, verbose_name='ФИО клиента')
    comment = models.CharField(blank=True, verbose_name='комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f'{self.client_fullname}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class NewsletterMessage(models.Model):
    newsletter_topic = models.CharField(max_length=500, verbose_name='тема рассылки')
    newsletter_message = models.TextField(max_length=30, verbose_name='сообщение рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f'{self.newsletter_topic}'

    class Meta:
        verbose_name = 'Тема рассылки'


class NewsletterSettings(models.Model):
    time = models.TimeField(verbose_name='Выбрать время')
    frequency = models.CharField(max_length=255, choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'),
                                                          ('monthly', 'Раз в месяц')], verbose_name='Периодичность')
    status = models.CharField(max_length=255,
                              choices=[('completed', 'Завершена'), ('created', 'Создана'), ('running', 'Запущена')],
                              verbose_name='Статус')
    message = models.ForeignKey("NewsletterMessage", on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    clients = models.ManyToManyField('Client', verbose_name='Клиент')  # Связь "многие ко многим" с моделью клиента
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    start_at = models.DateTimeField(default=datetime.now(), verbose_name='дата начала')
    finish_at = models.DateTimeField(default=timezone.now() + relativedelta(months=1), verbose_name='дата окончания')
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.message}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            (
                'set_status',
                'Can change status'
            )
        ]


class NewsletterLog(models.Model):
    sending = models.ForeignKey("NewsletterSettings", on_delete=models.CASCADE, verbose_name='рассылка')
    last_tried_at = models.DateTimeField(default=timezone.now, verbose_name='последняя попытка')
    status = models.BooleanField(default=False, verbose_name='статус')
    server_response = models.CharField(verbose_name='ответ почтового сервера', **NULLABLE)

    def __str__(self):
        str = f'{self.sending} {self.last_tried_at} '
        if self.status:
            str += 'успешная попытка отправки'
        else:
            str += f'ошибка: {self.server_response}'
        return str

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'
        ordering = ('last_tried_at',)

newsletter/forms.py
import json

from django import forms

from newsletter.models import Client, NewsletterMessage, NewsletterSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(forms.ModelForm, StyleFormMixin):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('owner',)


class NewsletterMessageForm(forms.ModelForm, StyleFormMixin):
    class Meta:
        model = NewsletterMessage
        fields = '__all__'
        exclude = ('owner',)


class NewsletterSettingsForm(forms.ModelForm, StyleFormMixin):
    class Meta:
        model = NewsletterSettings
        fields = '__all__'
        exclude = ('owner',)


class NewsletterSettingsModerationForm(NewsletterSettingsForm):
    class Meta:
        model = NewsletterSettings
        fields = '__all__'

newsletter/views.py
import random

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Permission
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from mainapp.models import Blog
from newsletter.forms import ClientForm, NewsletterMessageForm, NewsletterSettingsForm, NewsletterSettingsModerationForm
from newsletter.models import Client, NewsletterMessage, NewsletterSettings, NewsletterLog


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')
    template_name = 'newsletter/client_form.html'

    def form_valid(self, form):
        newsletter_settings = form.save(commit=False)  # Сохраняем форму без коммита в базу данных
        newsletter_settings.owner = self.request.user  # Устанавливаем владельца рассылки равным текущему пользователю
        newsletter_settings.save()  # Сохраняем изменения в базу данных
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')
    template_name = 'newsletter/client_form.html'

    def get_form_class(self):
        return super().get_form_class()

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     FormSet = inlineformset_factory(self.model, NewsletterMessage, form=NewsletterMessageForm, extra=1)
    #     if self.request.method == 'POST':
    #         formset = FormSet(self.request.POST, instance=self.object)
    #     else:
    #         formset = FormSet(instance=self.object)
    #     context_data['formset'] = formset
    #     return context_data
    #
    # def form_valid(self, form):
    #     context_data = self.get_context_data()
    #     formset = context_data['formset']
    #     with transaction.atomic():
    #         if form.is_valid():
    #             self.object = form.save()
    #             if formset.is_valid():
    #                 formset.instance = self.object
    #                 formset.save()
    #
    #     return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'newsletter/client_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Client
    form_class = ClientForm
    template_name = 'newsletter/client_form.html'

    def get_form_class(self):
        return super().get_form_class()

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('newsletter:client_list')
    template_name = 'newsletter/client_confirm_delete.html'
    permission_required = 'newsletter.delete_client'

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class NewsletterMessageCreateView(LoginRequiredMixin, CreateView):
    model = NewsletterMessage
    form_class = NewsletterMessageForm
    success_url = reverse_lazy('newsletter:newslettermessage_list')
    template_name = 'newsletter/newsletter_form.html'

    def form_valid(self, form):
        newsletter_settings = form.save(commit=False)  # Сохраняем форму без коммита в базу данных
        newsletter_settings.owner = self.request.user  # Устанавливаем владельца рассылки равным текущему пользователю
        newsletter_settings.save()  # Сохраняем изменения в базу данных
        return super().form_valid(form)


class NewsletterMessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = NewsletterMessage
    form_class = NewsletterMessageForm
    success_url = reverse_lazy('newsletter:newslettermessage_list')
    template_name = 'newsletter/newsletter_form.html'

    def get_form_class(self):
        return super().get_form_class()

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class NewsletterMessageListView(LoginRequiredMixin, ListView):
    model = NewsletterMessage
    template_name = 'newsletter/newsletter_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class NewsletterMessageDetailView(LoginRequiredMixin, DetailView):
    model = NewsletterMessage
    template_name = 'newsletter/newsletter_page.html'
    fields = '__all__'


class NewsletterMessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = NewsletterMessage
    form_class = NewsletterMessageForm
    success_url = reverse_lazy('newsletter:newslettermessage_list')
    template_name = 'newsletter/newsletter_confirm_delete.html'

    def get_form_class(self):
        return super().get_form_class()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object
        return context

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class NewsletterSettingsCreateView(LoginRequiredMixin, CreateView):
    model = NewsletterSettings
    form_class = NewsletterSettingsForm
    success_url = reverse_lazy('newsletter:mail_list')
    template_name = 'newsletter/mail_form.html'

    def get_form(self, form_class=None):
        form = super(NewsletterSettingsCreateView, self).get_form(form_class)
        form.fields['clients'].queryset = Client.objects.filter(owner=self.request.user)
        form.fields['message'].queryset = NewsletterMessage.objects.filter(owner=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(NewsletterSettingsCreateView, self).form_valid(form)


class NewsletterSettingsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = NewsletterSettings
    form_class = NewsletterSettingsForm
    success_url = reverse_lazy('newsletter:mail_list')
    template_name = 'newsletter/mail_form.html'

    def get_form_class(self):
        return super().get_form_class()

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class NewsletterSettingsListView(LoginRequiredMixin, ListView):
    model = NewsletterSettings
    template_name = 'newsletter/mail_list.html'

    def get_form_class(self):
        return super().get_form_class()

    def get_queryset(self):
        if self.request.user.has_perm('newslettersettings.view_newslettersettings'):
            return super().get_queryset()
        return super().get_queryset().filter(owner=self.request.user)


class NewsletterSettingsDetailView(LoginRequiredMixin, DetailView):
    model = NewsletterSettings
    form_class = NewsletterSettingsForm
    template_name = 'newsletter/mail_page.html'

    def get_form_class(self):
        return super().get_form_class()


class NewsletterSettingsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = NewsletterSettings
    success_url = reverse_lazy('newsletter:mail_list')
    template_name = 'newsletter/newsletter_confirm_delete.html'

    def get_form_class(self):
        return super().get_form_class()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object
        return context

    def test_func(self):
        owner = self.request.user
        if owner == self.request.user:
            return True
        return self.handle_no_permission()


class NewsletterLogListView(LoginRequiredMixin, ListView):
    model = NewsletterLog
    template_name = 'newsletter/log_list.html'

    def get_queryset(self):
        return super().get_queryset()

newsletter/templates/newsletter/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Удаление карточки клиента</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                <p>Удалить клиента {{ object }}?</p>
                    <button type="submit" class="btn btn-danger">Удалить</button>
            </div>
            <div class="card-footer">
                <a href="{% url 'newsletter:client_list' %}">Отмена</a>
            </div>
        </div>

    </div>
    </form>


{% endblock %}

newsletter/templates/newsletter/client_form.html
{% extends 'main/base.html' %}
{% block content %}



<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_list.html
{% extends 'main/base.html' %}

{% block content %}


    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'newsletter:create_client' %}">Создать нового клиента</a>
     <p></p>
    {% for client in client_list %}

        <div class="col">
            <div class="card shadow-sm">

              <div class="card-body">
                <p class="card-text">
                  Имя клиента: {{ client|title }}</p>
                  <p>Почта клиента: {{ client.client_email }}</p>
                  <p>Комментарий: {{client.comment}}</p>

                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'newsletter:edit_client' client.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'newsletter:delete_client' client.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
    </div>


{% endblock %}

newsletter/templates/newsletter/log_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4>История ваших рассылок</h4>
</div>
<div class="row">
    <div class="col-6">
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Рассылка</th>
                    <th scope="col">Cтатус</th>
                </tr>
                </thead>
                <tbody>
                {% for log in newsletterlog_list %}
                <tr>
                    <td>{{log.pk}}</td>
                    <td>{{log.sending}}  {{log.last_tried_at}}</td>
                    <td>{{log.status}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Удаление карточки рассылки</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                <p>Удалить рассылку {{ object }}?</p>
                    <button type="submit" class="btn btn-danger">Удалить</button>
            </div>
            <div class="card-footer">
                <a href="{% url 'newsletter:newslettermessage_list' %}">Отмена</a>
            </div>
        </div>

    </div>
    </form>


{% endblock %}

newsletter/templates/newsletter/mail_form.html
{% extends 'main/base.html' %}
{% block content %}


<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_list.html
{% extends 'main/base.html' %}

{% block content %}
    {% if not user.is_superuser or not user.is_staff %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'newsletter:create_mail' %}">Создать новую рассылку</a>
        <a class="btn btn-outline-primary" href="{% url 'newsletter:client_list' %}">Ваши Клиенты</a>
        <a class="btn btn-outline-primary" href="{% url 'newsletter:newslettermessage_list' %}">Ваши сообщения для рассылки</a>
        <a class="btn btn-outline-primary" href="{% url 'newsletter:log_list' %}">История ваших рассылок</a>
     <p></p>

    {% endif %}
        <span class="fw-bold">Ваши рассылки</span>
     </p>

    {% for newslettersettings in newslettersettings_list %}

        <div class="col">
            <div class="card shadow-sm">

              <div class="card-body">
                <p class="card-text">
                    Тема рассылки: <span class="fw-bold">{{ newslettersettings.message.newsletter_topic }}</span>
                </p>

                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'newsletter:view_mail' newslettersettings.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    <a href="{% url 'newsletter:edit_mail' newslettersettings.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'newsletter:delete_mail' newslettersettings.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
    </div>


{% endblock %}

newsletter/templates/newsletter/mail_page.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <span class="fw-bold">{{ newslettersettings|title }}</span>
                    <p></p>
                    <p class="card-text">
                        <p>
                            <p>Клиенты:</p>
                            <ul>
                                {% for client in newslettersettings.clients.all %}
                                <li>{{ client.client_fullname }}</li>
                                {% endfor %}
                            </ul>
                        </p>
                        <p>Статус рассылки: {{newslettersettings.status }}</p>
                        <p>Периодичность рассылки: {{newslettersettings.frequency }}</p>
                        <p>Время отправки рассылки: {{newslettersettings.time }}</p>
                        <p>Текст рассылки: {{newslettersettings.message.newsletter_message }}</p>
                    <p>
                        <a href="{% url 'newsletter:mail_list' %}" class="btn btn-warning">Назад</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Удаление карточки рассылки</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                <p>Удалить рассылку {{ object }}?</p>
                    <button type="submit" class="btn btn-danger">Удалить</button>
            </div>
            <div class="card-footer">
                <a href="{% url 'newsletter:newslettermessage_list' %}">Отмена</a>
            </div>
        </div>

    </div>
    </form>


{% endblock %}

newsletter/templates/newsletter/newsletter_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends 'main/base.html' %}

{% block content %}


    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'newsletter:create_newslettermessage' %}">Создать сообщение рассылки</a>
     <p></p>
        <span class="fw-bold">Ваши сообщения рассылки</span>
     </p>

    {% for newslettermessage in newslettermessage_list %}

        <div class="col">
            <div class="card shadow-sm">

              <div class="card-body">
                <p class="card-text">
                  {{ newslettermessage|title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'newsletter:view_newslettermessage' newslettermessage.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    <a href="{% url 'newsletter:edit_newslettermessage' newslettermessage.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'newsletter:delete_newslettermessage' newslettermessage.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
    </div>


{% endblock %}

newsletter/templates/newsletter/newsletter_page.html
{% extends 'main/base.html' %}
{% block content %}



                <span class="fw-bold"> {{ newslettermessage.newsletter_topic }} </span>
               <p>
                </p>
                <p class="card-text"><p>

                  {{ newslettermessage.newsletter_message }}
                <p>
                <a href="{% url 'newsletter:newslettermessage_list' %}" class="btn btn-warning">Назад</a>
                </p>



{% endblock %}