config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.contrib import admin
from mainapp.views import BlogCreateView, BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView, toggle_activity
from django.views.decorators.cache import cache_page

from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [

    path('blog_form_create/', BlogCreateView.as_view(), name='blog_form_create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/blog_detail/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/blog_form/', BlogUpdateView.as_view(), name='blog_form'),
    path('<int:pk>/blog_confirm_delete/', BlogDeleteView.as_view(), name='blog_confirm_delete'),
    path('<int:pk>/activity/', toggle_activity, name='toggle_activity'),

]

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter import views
from newsletter.apps import NewsletterConfig
from newsletter.views import ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    NewsletterMessageListView, NewsletterMessageDetailView, NewsletterMessageCreateView, NewsletterMessageUpdateView, \
    NewsletterMessageDeleteView, NewsletterSettingsListView, NewsletterSettingsDetailView, NewsletterSettingsCreateView, \
    NewsletterSettingsUpdateView, NewsletterSettingsDeleteView, NewsletterLogListView

app_name = NewsletterConfig.name


urlpatterns = [

    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/view/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('newslettermessage/', NewsletterMessageListView.as_view(), name='newslettermessage_list'),
    path('newslettermessage/view/<int:pk>/', NewsletterMessageDetailView.as_view(), name='view_newslettermessage'),
    path('newslettermessage/create/', NewsletterMessageCreateView.as_view(), name='create_newslettermessage'),
    path('newslettermessage/edit/<int:pk>/', NewsletterMessageUpdateView.as_view(), name='edit_newslettermessage'),
    path('newslettermessage/delete/<int:pk>/', NewsletterMessageDeleteView.as_view(), name='delete_newslettermessage'),

    path('newslettersettings/', cache_page(60)(NewsletterSettingsListView.as_view()), name='mail_list'),
    path('newslettersettings/view/<int:pk>/', NewsletterSettingsDetailView.as_view(), name='view_mail'),
    path('newslettersettings/create/', NewsletterSettingsCreateView.as_view(), name='create_mail'),
    path('newslettersettings/edit/<int:pk>/', NewsletterSettingsUpdateView.as_view(), name='edit_mail'),
    path('newslettersettings/delete/<int:pk>/', NewsletterSettingsDeleteView.as_view(), name='delete_mail'),

    path('log_list', cache_page(60)(NewsletterLogListView.as_view()), name='log_list'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import generate_new_password, verification, ProfileUpdateView, UserListView, \
    status_user, RegisterUserView, UserLoginView, UserLogoutView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password'),
    path('verification/<str:code>/', verification, name='verification'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('status_user/<int:pk>', status_user, name='status_user'),
]

mainapp/models.py
from django.db import models

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    blog_title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='url для пользователя')
    description = models.TextField(max_length=500, verbose_name='содержимое')
    blog_image = models.ImageField(upload_to='photo_blog/', verbose_name='изображение', **NULLABLE)
    blog_date = models.DateTimeField(verbose_name='дата создания', **NULLABLE)
    blog_is_published = models.BooleanField(default=True, verbose_name='опубликован')
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.blog_title}'

    class Meta:
        verbose_name = 'блоговая запись'
        verbose_name_plural = 'блоговые записи'
        ordering = ('blog_title',)

mainapp/forms.py
from django import forms

from mainapp.models import Blog


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(forms.ModelForm, StyleFormMixin):
    class Meta:
        model = Blog
        # fields = '__all__'
        fields = ('blog_title', 'description', 'blog_image', 'blog_date', 'blog_is_published')
        #exclude = ('product_user', )

mainapp/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from mainapp.forms import BlogForm
from mainapp.models import Blog
from newsletter.models import NewsletterSettings, Client


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mainapp:blog_list')
    template_name = 'main/blog_form.html'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.blog_title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mainapp:blog_list')
    template_name = 'main/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['newslettersettings_count'] = NewsletterSettings.objects.all().count()
        context_data['active_newslettersettings_count'] = NewsletterSettings.objects.filter(is_active=True).count()
        blog_list = list(Blog.objects.all())
        context_data['blog_list'] = blog_list[:3]
        context_data['clients_count'] = Client.objects.all().count()
        return context_data


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mainapp:blog_detail')
    template_name = 'main/blog_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'main/blog_form.html'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.blog_title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mainapp:blog_list')
    template_name = 'main/blog_confirm_delete.html'


@login_required

def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.blog_is_published:
        blog_item.blog_is_published = False
    else:
        blog_item.blog_is_published = True

    blog_item.save()

    return redirect(reverse('mainapp:blog_list'))

mainapp/templates/main/base.html
 {% load static %}
<!doctype html>

<html lang="en" data-bs-theme="auto">
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>{{ title }}</title>



<link href="{% static 'css/bootstrap.min.css' %}"
      rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


  </head>
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4></h4>
          <p class="text-body-secondary">Simple and fast</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Меню</h4>
          <ul class="list-unstyled">

            {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
            <form action="{% url 'users:logout' %}" method="post" class="text-white">
              {% csrf_token %}
              <button type="submit">Выйти</button>
            </form>
            {% else %}
              <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
              <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong></strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Newsletter</h1>
        <p class="lead text-body-secondary">Blogging and Newsletter</p>
        <p>
          <a href="{% url 'mainapp:blog_list' %}" class="btn btn-secondary my-2">Главная</a>
          {% if user.is_authenticated %}
          <a href="{% url 'newsletter:mail_list' %}" class="btn btn-secondary my-2">Все рассылки</a>
          {% endif %}
          {% if user.is_staff or user.is_superuser %}
          <a href="{% url 'users:user_list' %}" class="btn btn-secondary my-2">Все пользователи</a>
          {% endif %}
        </p>
        <span class="fw-bold">Добро пожаловать
          {% if user.is_authenticated %}
          {{ user|title }}
          {% else %}
          Гость
           {% endif %}</span>
      </div>
    </div>
  </section>


  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      {% block content %}
      {% endblock %}


    </div>
  </div>

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p>&copy; 2023 - {% now 'Y' %}</p>
  </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>
</html>

mainapp/templates/main/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить "{{ blog.blog_title }}"?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'mainapp:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/main/blog_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

            <svg class="bd-placeholder-img card-img-top" width="150%" height="275" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false" style="background-color: white;">
              {% if blog.blog_image %}
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"
                     style="background-color: white;"><image xlink:href="{{ blog|get_image }}" width="100%" height="100%" /></svg>
              {% else %}
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"
                     style="background-color: white;"><image xlink:href="{{ '/media/photo_blog/no_photo.png' }}" width="100%" height="100%" /></svg>
              {% endif %}
            </svg>

      <div class="cols-12">
          <div class="row">
            <div class="col-6">

              <div class="card">
                <div class="card-holder">
                    <h3 class="card-title">
                        "{{ blog.blog_title }}"({{ blog.slug }})
                    </h3>

                </div>

                <div class="card-body">
                    <p>
                        {{ blog.description }}
                    </p>
                    <p>
                        {{ blog.blog_date }}
                    </p>
                     <a href="{% url 'mainapp:blog_list' %}" class="btn btn-warning">Назад</a>
                </div>
              <div class="card-footer">
                 Просмотры: {{ blog.view_count }}
              </div>
              </div>

            </div>
          </div>
      </div>


{% endblock %}

mainapp/templates/main/blog_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}


<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 rounded-3">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Общее количество рассылок</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ newslettersettings_count }}</h1>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4 rounded-3">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Количество активных рассылок</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ active_newslettersettings_count }}</h1>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4 rounded-3">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Количество клиентов сервиса</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ clients_count }}</h1>
            </div>
        </div>
    </div>
</div>
{% if user.is_authenticated %}

    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'mainapp:blog_form_create' %}">Создать новый блог</a>
{% endif %}

    {% for blog in blog_list %}

        <div class="col">
            <div class="card shadow-sm">
              {% if blog.blog_image %}
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"
                     style="background-color: white;"><image xlink:href="{{ blog|get_image }}" width="100%" height="100%" /></svg>
              {% else %}
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"
                     style="background-color: white;"><image xlink:href="{{ '/media/photo_blog/no_photo.png' }}" width="100%" height="100%" /></svg>
              {% endif %}
              <div class="card-body">
                <p class="card-text">
                  {{ blog|title }}
                </p>
                <p>{{ blog.blog_date }} </p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mainapp:blog_detail' blog.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотреть</a>
                    {% if user.is_superuser %}
                    <a href="{% url 'mainapp:blog_form' blog.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'mainapp:blog_confirm_delete' blog.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
                </div>
                {% if blog.blog_is_published %}
                <a class="btn btn-warning" href="{% url 'mainapp:toggle_activity' blog.pk %}">Отмена публикации</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'mainapp:toggle_activity' blog.pk %}">Опубликовать</a>
                {% endif %}
              {% endif %}

              </div>
            </div>
          </div>
    {% endfor %}
    </div>



{% endblock %}