config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import generate_new_password, verification, ProfileUpdateView, UserListView, \
    status_user, RegisterUserView, UserLoginView, UserLogoutView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password'),
    path('verification/<str:code>/', verification, name='verification'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('status_user/<int:pk>', status_user, name='status_user'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта пользователя')
    phone = models.CharField(max_length=35, verbose_name='телефон пользователя', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар пользователя', **NULLABLE)
    verify_code = models.CharField(max_length=10, verbose_name='код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = [
            (
                'set_is_active',
                'Can deactivate user'
            )
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from mainapp.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserListForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone')

users/views.py
import random
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib.auth.models import User

from config import settings

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, UserListForm
from users.models import User


class UserLoginView(LoginView):
    model = User
    success_url = reverse_lazy('newsletter:newslettermessage_list')
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    model = User
    success_url = reverse_lazy('blog:blog_list')


class RegisterUserView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def get_success_message(self, cleaned_data):
        return ('Вам на почту отправлено письмо, '
                'для прохождения верификации перейдите по ссылку в письме')

    def form_valid(self, form):
        """Верификация по ссылке через почту"""
        new_user = form.save()
        code = ''.join(random.sample('0123456789', 6))
        new_user.verify_code = code
        new_user.is_active = False
        print('new_user.email')
        send_mail(
            'Верификация',
            f'Перейдите по ссылке для верификации: '
            f'http://127.0.0.1:8000/users/verification/{code}',
            EMAIL_HOST_USER,
            [new_user.email]
        )
        return super().form_valid(form)


def verification(request, code):
    user = User.objects.get(verify_code=code)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """Отключаем необходимость получения pk, получая его из запроса"""
        return self.request.user


def generate_new_password(request):
    new_pass = User.objects.make_random_password()
    request.user.set_password(new_pass)
    request.user.save()
    send_mail(
        'Вы сменили пароль ',
        f'Ваш новый пароль: {new_pass}',
        EMAIL_HOST_USER,
        [request.user.email]
    )
    messages.success(request,
                     'Вам на почту отправлено письмо '
                     'с новым паролем для вашего аккаунта')
    return redirect(reversed('mainapp:blog_list'))


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    form_class = UserListForm

    def test_func(self):
        return self.request.user.is_staff


@permission_required('users.set_is_active')
def status_user(request, pk):
    """Контроллер смены статуса пользователя"""
    user = User.objects.get(pk=pk)
    if not user.is_superuser:
        if user.is_active is True:
            user.is_active = False
            user.save()
        elif user.is_active is False:
            user.is_active = True
            user.save()
        return redirect(reverse('users:user_list'))

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Вход</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
            </div>
        </div>

    </div>
    </form>


{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Регистрация</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-success">
                        Регистрация
                    </button>
            </div>
        </div>

    </div>
    </form>


{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
    <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Профиль</h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
            <div class="card-footer">
            <a href="{% url 'users:generate_new_password'%}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
            </div>
        </div>

    </div>
    </form>
    </div>


{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4>Зарегистрированные пользователи</h4>
</div>
<div class="row">
    <div class="col-6">
        <div class="table-responsive small">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Почта</th>
                    <th scope="col">Телефон</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                <tr>
                    <td>{{user.email}}</td>
                    <td>{{user.phone}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}